# Generated by Django 5.0.2 on 2024-03-09 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0015_remove_publications_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailPer', models.EmailField(blank=True, default='invitado', max_length=254)),
                ('fechaPub', models.DateField()),
                ('horaPub', models.TimeField()),
                ('comPub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publications')),
            ],
        ),
    ]
