# Generated by Django 5.0.2 on 2024-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='contenido',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='emailPer',
            field=models.CharField(blank=True, default='invitado', max_length=20),
        ),
    ]
