# Generated by Django 5.0.2 on 2024-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentarios_contenido_alter_comentarios_emailper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='emailPer',
            field=models.CharField(blank=True, default='invitado', max_length=100),
        ),
    ]
