# Generated by Django 5.0.2 on 2024-03-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0016_publications_aprobada_alter_publications_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailPer', models.EmailField(max_length=254)),
                ('pdf', models.FileField(blank=True, upload_to='')),
                ('modalidad', models.CharField(max_length=20)),
                ('solPub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publications')),
            ],
        ),
    ]
