# Generated by Django 5.0.2 on 2024-03-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
