# Generated by Django 5.0.2 on 2024-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaCierre', models.DateField(blank=True)),
                ('horaInicio', models.TimeField()),
                ('horaCierre', models.TimeField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
