# Generated by Django 5.0.2 on 2024-03-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_rename_notificaciones_personas_cantnotificaciones'),
        ('sesion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='idPer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.personas'),
        ),
    ]
