# Generated by Django 5.0.2 on 2024-03-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
