# Generated by Django 5.0.2 on 2024-03-01 03:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0002_alter_personas_catdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('fechaEvento', models.DateField()),
                ('limiteEntrega', models.DateField()),
                ('emailEvento', models.EmailField(max_length=254)),
                ('enlace', models.URLField()),
                ('tematicas', models.TextField()),
                ('pdf', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(100)])),
                ('foto', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(100)])),
                ('publicacionesPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.personas')),
            ],
        ),
    ]
