# Generated by Django 5.0.2 on 2024-03-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
