# Generated by Django 5.0.2 on 2024-03-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publications_foto_alter_publications_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
