# Generated by Django 5.0.2 on 2024-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_publications_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pdfs/'),
        ),
    ]
