# Generated by Django 5.0.2 on 2024-03-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_publications_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
