# Generated by Django 5.0.2 on 2024-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_alter_publications_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='likes',
            field=models.TextField(),
        ),
    ]
