# Generated by Django 5.0.2 on 2024-03-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_alter_publications_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='comentarios',
        ),
    ]
