# Generated by Django 5.0.2 on 2024-03-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_remove_publications_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='aprobada',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='likes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
