# Generated by Django 5.0.2 on 2024-03-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_publications_aprobada_alter_publications_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='fechaFinEvento',
            field=models.DateField(blank=True, default='2024-03-29'),
        ),
    ]
