# Generated by Django 5.0.2 on 2024-03-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0006_personas_notificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('fechaEvento', models.DateField()),
                ('limiteEntrega', models.DateField()),
                ('emailEvento', models.EmailField(max_length=254)),
                ('enlace', models.URLField()),
                ('tematicas', models.TextField()),
                ('pdf', models.FileField(blank=True, upload_to='pdfs/')),
                ('foto', models.ImageField(blank=True, upload_to='pdfs/')),
                ('likes', models.TextField(blank=True)),
                ('publicacionesPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.personas')),
            ],
        ),
    ]
