# Generated by Django 5.0.2 on 2024-03-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0007_rename_notificaciones_personas_cantnotificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('contenido', models.TextField()),
                ('resumen', models.TextField()),
                ('fechaNot', models.DateField()),
                ('horaNot', models.TimeField()),
                ('notificacionesPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.personas')),
            ],
        ),
    ]
