# Generated by Django 5.0.2 on 2024-03-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_personas_catdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='contr',
            field=models.CharField(max_length=100),
        ),
    ]
