# Generated by Django 5.0.2 on 2024-03-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_personas_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='notificaciones',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
