# Generated by Django 5.0.2 on 2024-03-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_personas_notificaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='notificaciones',
            new_name='cantNotificaciones',
        ),
    ]
